name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v7

    - name: Build
      run: |
        xcodebuild -project StepTracker.xcodeproj \
          -scheme StepTracker \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          CODE_SIGNING_ALLOWED=NO \
          build
